# Generated by Django 5.0.9 on 2024-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Completed'), (3, 'Failed')], default=1),
        ),
    ]
