# Generated by Django 5.0.9 on 2024-10-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_enrollment_status_enrollment_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='language',
            new_name='status',
        ),
    ]
