# Generated by Django 5.0.9 on 2024-10-17 23:58

import lumofy_task.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[lumofy_task.files.models.validate_file_size]),
        ),
    ]
